/*
  Nathan Nguyen
  CSC 352
  Assignment 1
  September 20th, 2021
*/

-- 1
SELECT EMPLOYEE_ID, FIRST_NAME || ' ' || LAST_NAME as FULL_NAME, JOB_ID, SALARY
    FROM EMPLOYEES 
    WHERE DEPARTMENT_ID = 60;
    
-- 2
SELECT FIRST_NAME || ' ' || LAST_NAME as FULL_NAME, EMPLOYEES.DEPARTMENT_ID, DEPARTMENTS.DEPARTMENT_NAME, SALARY
    FROM EMPLOYEES LEFT OUTER JOIN DEPARTMENTS
        ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID
    WHERE EMPLOYEES.JOB_ID = 'IT_PROG';
    
-- 3
SELECT DEPARTMENTS.DEPARTMENT_ID, DEPARTMENTS.DEPARTMENT_NAME, COUNT(DISTINCT EMPLOYEE_ID)
    FROM DEPARTMENTS JOIN EMPLOYEES
        ON DEPARTMENTS.DEPARTMENT_ID = EMPLOYEES.DEPARTMENT_ID
    HAVING COUNT(DISTINCT EMPLOYEE_ID) <> 0
    GROUP BY DEPARTMENTS.DEPARTMENT_ID, DEPARTMENTS.DEPARTMENT_NAME
    ORDER BY COUNT(DISTINCT EMPLOYEE_ID);

-- 4
SELECT A.FIRST_NAME || ' ' || A.LAST_NAME as FULL_NAME, B.FIRST_NAME || ' ' || B.LAST_NAME as MANAGER_NAME
    FROM EMPLOYEES A JOIN EMPLOYEES B
        ON A.MANAGER_ID = B.EMPLOYEE_ID
    WHERE A.DEPARTMENT_ID IS NULL;
    
-- 5
SELECT DEPARTMENT_ID, MAX(SALARY + SALARY * NVL(COMMISSION_PCT, 0)) as HIGHEST_SALARY, MIN(SALARY + SALARY * NVL(COMMISSION_PCT, 0)) as LOWEST_SALARY
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID IS NOT NULL
    GROUP BY DEPARTMENT_ID;

-- 6
SELECT EMPLOYEE_ID, LAST_NAME, FIRST_NAME, DEPARTMENT_ID
    FROM EMPLOYEES
    WHERE LAST_NAME IN (
        SELECT LAST_NAME
            FROM EMPLOYEES
            GROUP BY LAST_NAME
            HAVING COUNT(*) > 1
        );
        
-- 7
SELECT LAST_NAME, FIRST_NAME, EMPLOYEES.MANAGER_ID, DEPARTMENTS.MANAGER_ID
    FROM EMPLOYEES FULL OUTER JOIN DEPARTMENTS
        ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID
    WHERE EMPLOYEES.DEPARTMENT_ID IN (10,20,30,40,60)
    AND EMPLOYEES.MANAGER_ID != DEPARTMENTS.MANAGER_ID;
    
-- 8
SELECT LAST_NAME, FIRST_NAME, SALARY + SALARY * NVL(COMMISSION_PCT, 0) AS SALARY, EMPLOYEES.DEPARTMENT_ID
    FROM EMPLOYEES, DEPARTMENTS
    WHERE EMPLOYEE_ID IN DEPARTMENTS.MANAGER_ID
    AND EMPLOYEE_ID NOT IN EMPLOYEES.MANAGER_ID;

-- 9
declare
    l_name EMPLOYEES.LAST_NAME%type;
    sal EMPLOYEES.SALARY%type;

begin
    l_name := 'Jackson';
    sal := 8888;
    dbms_output.put_line('Last Name: ' || l_name);
    dbms_output.put_line('Salary: ' || TO_CHAR(sal, '$9,999.99'));

end;

-- 10
<<OUTER_BLOCK>>
declare
    counter integer := 1;
    name varchar2(30) := 'Fred';
    
begin
    <<INNER_BLOCK>>
    declare
        counter integer := 99;
    begin
        dbms_output.put_line('Outer Counter: ' || OUTER_BLOCK.counter);
        dbms_output.put_line('Inner Counter: ' || counter);
        dbms_output.put_line('Name: ' || OUTER_BLOCK.name);
    end;
end;
        